// <auto-generated />
using LiveStreams.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiveStreams.Api.Data.Migrations
{
    [DbContext(typeof(LiveStreamsAppContext))]
    [Migration("20180910230553_initial_create")]
    partial class initial_create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LiveStreams.Api.Models.ChannelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Branding");

                    b.Property<string>("BrandingImage");

                    b.Property<string>("ChannelId");

                    b.Property<string>("Description");

                    b.Property<string>("StreamUrl");

                    b.Property<string>("SubscriptionId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
